### ISSUE TITLE
[JOSS REVIEW] Suggestions for Documentation

### ISSUE THREAD

**Issue by xin-huang** [jonotuke/BREADR#3]
This is part of the JOSS review (https://github.com/openjournals/joss-reviews/issues/7916)

**Installation instructions:** According to the reference manual (https://cran.r-project.org/web/packages/BREADR/BREADR.pdf), the package requires R version ≥ 2.10. However, I was unable to install the package from CRAN using R 4.1.2. 

It would be helpful to include the link to the package website (https://jonotuke.github.io/BREADR/) in the README file, so that users can more easily locate the reference manual and other documentation.

**Example usage:** It would be helpful to include a direct link to the dataset for easier testing.

https://github.com/jonotuke/BREADR/blob/36b86a2c925ca92b49e882629fb404e7f85f281d/README.md?plain=1#L72-L75

For example,

```
 Note that since the Eigenstrat files are too large to include, we 
 provide a pre-processed data set called [counts_example](https://github.com/jonotuke/BREADR/blob/master/data/counts_example.rda) which is the 
 product of running processEigenstrat() on real data (although the raw 
 Eigenstrat files can be found on [the Github page](https://github.com/jonotuke/BREADR/tree/master/data-raw)). 
```

**Automated tests:** Automated tests are present, but currently failing. I recommend the authors fix the test suite.

**Community guidelines:** There are no clear guidelines for contributing to the software. I suggest adding contribution guidelines to encourage community involvement.

**Comment by jonotuke** [comment]
>Installation instructions: According to the reference manual (https://cran.r-project.org/web/packages/BREADR/BREADR.pdf), the package requires R version ≥ 2.10. However, I was unable to install the package from CRAN using R 4.1.2.

I have updated to a later version of R.

**Comment by jonotuke** [comment]
> It would be helpful to include the link to the package website (https://jonotuke.github.io/BREADR/) in the README file, so that users can more easily locate the reference manual and other documentation.

Done.

**Comment by jonotuke** [comment]
> Example usage: It would be helpful to include a direct link to the dataset for easier testing.

Add to example pipeline vignette.

**Comment by jonotuke** [comment]
> Automated tests: Automated tests are present, but currently failing. I recommend the authors fix the test suite.

Done

**Comment by xin-huang** [comment]
Unfortunately, I am still unable to install the package using R 4.2.3 and the command:

```
install.packages("BREADR")
```

I encountered the following errors:

```
ERROR: dependencies ‘cowplot’, ‘ggplot2’, ‘MASS’, ‘Matrix’ are not available for package ‘doBy’
ERROR: dependencies ‘lme4’, ‘MASS’, ‘Matrix’, ‘doBy’ are not available for package ‘pbkrtest’
ERROR: dependencies ‘MASS’, ‘mgcv’, ‘pbkrtest’, ‘quantreg’, ‘lme4’ are not available for package ‘car’
ERROR: dependency ‘car’ is not available for package ‘rstatix’
ERROR: dependencies ‘ggplot2’, ‘ggrepel’, ‘ggsci’, ‘cowplot’, ‘ggsignif’, ‘rstatix’ are not available for package ‘ggpubr’
ERROR: dependencies ‘data.table’, ‘ggplot2’, ‘ggpubr’, ‘MASS’ are not available for package ‘BREADR’
```

Some packages that appear necessary for installation, such as `Matrix`, are not explicitly declared under Imports or Depends. It would be helpful to add them to the `DESCRIPTION` file to avoid installation failures. It would also be helpful if the required R version and necessary dependencies could be mentioned in the README or on the [BREADR website](https://jonotuke.github.io/BREADR/), so that users are aware before installation.

Moreover, when I tried to install Matrix using `install.packages("Matrix")`, I received the following message:

```
package ‘Matrix’ is not available for this version of R
‘Matrix’ version 1.7-3 is in the repositories but depends on R (>= 4.4)
‘Matrix’ version 1.7-3 is in the repositories but depends on R (>= 4.6)
‘Matrix’ version 1.7-3 is in the repositories but depends on R (>= 4.5)
```

So it appears that the actual R version requirement is ≥ **4.4**, not ≥ 4.2 as currently specified in the `DESCRIPTION` file. This should be updated accordingly to prevent installation failures.

I also noticed that in the [DESCRIPTION](https://github.com/jonotuke/BREADR/blob/376d901609c967197211cbe8fd7dd8de24cd7c79/DESCRIPTION#L68) file, the required R version is set to `>= 4.2`. However, the [CRAN reference manual](https://cran.r-project.org/web/packages/BREADR/BREADR.pdf) still lists the R version requirement as `>= 2.10`. You might want to update that as well for consistency.

**Comment by xin-huang** [comment]
I noticed that in your GitHub Actions workflow, the package is tested with `release`, `devel`, and `oldrel-1`:

https://github.com/jonotuke/BREADR/blob/376d901609c967197211cbe8fd7dd8de24cd7c79/.github/workflows/R-CMD-check.yaml#L17-L25

Since the current release is R 4.4, this means that versions such as R 4.2.x are not actually being tested. Therefore, the declared dependency R (>= 4.2) in the DESCRIPTION file is not currently verified by the test matrix.

**Comment by jonotuke** [comment]
I have added the dependencies to the README file. 

I have added the Matrix package as a Suggests. The package checking that I run will not allow Matrix to be added as an Imports as it is not use directly. 

I have set the current R version requirement to >=4.4

@jonotuke

**Comment by xin-huang** [comment]
I still cannot install the package with R version 4.3.3, although it installs successfully with R version 4.4.3. As noted above, the `Matrix` package on CRAN now requires R ≥ 4.4. While the CI environment likely uses pre-installed or version-matched packages via RSPM or binary mirrors, this masks actual version compatibility problems. Therefore, CI passing alone is not sufficient to demonstrate practical installability—manual testing on a clean R 4.3 setup should be part of the validation process. I recommend that you explicitly state that the package requires R ≥ 4.4.

Additionally, I noticed that the [CRAN reference manual](https://cran.r-project.org/web/packages/BREADR/BREADR.pdf) still lists the R version requirement as R ≥ 2.10. This should be updated to reflect the current minimum version required for installation.
